const DIFFICULTIES={easy:{rows:9,cols:9,mines:10},medium:{rows:16,cols:16,mines:40},hard:{rows:16,cols:30,mines:99}};
const $=id=>document.getElementById(id); const boardElement=$('board'),difficultyElement=$('difficulty'),newGameButton=$('new-game'),mineCountElement=$('mine-count'),flagCountElement=$('flag-count'),timerElement=$('timer'),bestTimeElement=$('best-time'),messageElement=$('message'),themeToggle=$('theme-toggle'),soundToggle=$('sound-toggle'),winsElement=$('wins'),gamesElement=$('games'),winRateElement=$('win-rate'),pauseButton=$('pause-game'),hintButton=$('hint-button'),dailyButton=$('daily-button'),dailyStatus=$('daily-status');
let rows=9,cols=9,mineTotal=10,cells=[],started=false,gameOver=false,revealedCount=0,flags=0,seconds=0,timerId=null,paused=false,hintUsed=false,dailyMode=false,audioContext=null;
const get=(k,d=null)=>{try{const v=localStorage.getItem(k);return v===null?d:v}catch(_){return d}}; const set=(k,v)=>{try{localStorage.setItem(k,v)}catch(_){}};
function createCell(r,c){return{row:r,col:c,mine:false,revealed:false,flagged:false,adjacent:0,element:null}}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function buildBoard(){cells=[];boardElement.replaceChildren();boardElement.style.gridTemplateColumns=`repeat(${cols},34px)`;for(let r=0;r<rows;r++){const line=[];for(let c=0;c<cols;c++){const cell=createCell(r,c),b=document.createElement('button');b.className='cell';b.type='button';b.setAttribute('role','gridcell');b.addEventListener('click',()=>reveal(r,c));b.addEventListener('contextmenu',e=>{e.preventDefault();toggleFlag(r,c)});cell.element=b;line.push(cell);boardElement.appendChild(b)}cells.push(line)}}
function neighbors(r,c){const a=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const rr=r+dr,cc=c+dc;if(rr>=0&&rr<rows&&cc>=0&&cc<cols)a.push(cells[rr][cc])}return a} const all=()=>cells.flat();
function placeMines(fr,fc){const safe=new Set([`${fr},${fc}`,...neighbors(fr,fc).map(x=>`${x.row},${x.col}`)]);let candidates=all().filter(x=>!safe.has(`${x.row},${x.col}`));if(candidates.length<mineTotal)candidates=all().filter(x=>x.row!==fr||x.col!==fc);shuffle(candidates);for(let i=0;i<mineTotal;i++)candidates[i].mine=true;all().forEach(x=>x.adjacent=neighbors(x.row,x.col).filter(n=>n.mine).length)}
function startTimer(){if(timerId!==null||paused)return;timerId=setInterval(()=>{seconds++;timerElement.textContent=seconds},1000)} function stopTimer(){if(timerId!==null){clearInterval(timerId);timerId=null}}
function updateCounters(){mineCountElement.textContent=Math.max(0,mineTotal-flags);flagCountElement.textContent=flags}
function best(){const n=Number(get(`ms-best-${difficultyElement.value}`,''));return Number.isFinite(n)&&n>0?n:null} function updateBest(){const b=best();bestTimeElement.textContent=b===null?'—':`${b}s`}
function stats(){return{games:Number(get('ms-games','0'))||0,wins:Number(get('ms-wins','0'))||0}} function renderStats(){const s=stats();winsElement.textContent=s.wins;gamesElement.textContent=s.games;winRateElement.textContent=`${s.games?Math.round(s.wins/s.games*100):0}%`} function record(win){const s=stats();s.games++;if(win)s.wins++;set('ms-games',s.games);set('ms-wins',s.wins);renderStats()}
function playSound(type){if(get('ms-sound','on')==='off')return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;if(!audioContext)audioContext=new C;if(audioContext.state==='suspended')audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain(),f={reveal:440,flag:660,lose:110,win:880};o.frequency.value=f[type]||440;o.type=type==='lose'?'sawtooth':'sine';g.gain.setValueAtTime(.0001,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.05,audioContext.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+.1);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.11)}catch(_){} }
function renderCell(x){const e=x.element;e.className='cell';e.textContent='';if(x.flagged&&!x.revealed){e.classList.add('flagged');e.textContent='🚩';return}if(!x.revealed)return;e.classList.add('revealed');if(x.mine){e.classList.add('mine');e.textContent='💣'}else if(x.adjacent)e.textContent=x.adjacent}
function flood(start){const q=[start],seen=new Set();while(q.length){const x=q.shift(),k=`${x.row},${x.col}`;if(seen.has(k)||x.revealed||x.flagged||x.mine)continue;seen.add(k);x.revealed=true;revealedCount++;renderCell(x);if(!x.adjacent)neighbors(x.row,x.col).forEach(n=>{if(!n.revealed&&!n.flagged&&!n.mine)q.push(n)})}}
function reveal(r,c){if(gameOver||paused)return;const x=cells[r][c];if(x.flagged)return;if(x.revealed){chord(x);return}if(!started){started=true;placeMines(r,c);startTimer();messageElement.textContent='Find every safe cell!'}if(x.mine){x.revealed=true;renderCell(x);lose();return}flood(x);playSound('reveal');checkWin()}
function chord(x){if(!started||!x.adjacent)return;const a=neighbors(x.row,x.col);if(a.filter(n=>n.flagged).length!==x.adjacent)return;for(const n of a){if(n.flagged||n.revealed)continue;if(n.mine){n.revealed=true;renderCell(n);lose();return}flood(n)}checkWin()}
function toggleFlag(r,c){if(gameOver||paused)return;const x=cells[r][c];if(x.revealed)return;if(!x.flagged&&flags>=mineTotal)return;x.flagged=!x.flagged;flags+=x.flagged?1:-1;renderCell(x);updateCounters();playSound('flag')}
function revealMines(){all().forEach(x=>{if(x.mine){x.revealed=true;renderCell(x)}})}
function lose(){if(gameOver)return;gameOver=true;stopTimer();revealMines();record(false);playSound('lose');messageElement.textContent='💥 Mine hit! Try again.'}
function checkWin(){if(revealedCount!==rows*cols-mineTotal)return;gameOver=true;stopTimer();all().forEach(x=>{if(x.mine&&!x.flagged){x.flagged=true;flags++;renderCell(x)}});updateCounters();record(true);const b=best();const nr=b===null||seconds<b;if(nr)set(`ms-best-${difficultyElement.value}`,seconds);updateBest();playSound('win');messageElement.textContent=nr?`🏆 NEW RECORD — ${seconds}s!`:`🎉 Victory in ${seconds}s!`}
function newGame(){const d=DIFFICULTIES[difficultyElement.value];rows=d.rows;cols=d.cols;mineTotal=d.mines;started=false;gameOver=false;revealedCount=0;flags=0;seconds=0;paused=false;hintUsed=false;dailyMode=false;stopTimer();timerElement.textContent='0';pauseButton.textContent='⏸ Pause';hintButton.disabled=false;messageElement.textContent='Click a cell to start.';buildBoard();updateCounters();updateBest();dailyStatus.textContent='Ready'}
function togglePause(){if(gameOver)return;paused=!paused;if(paused){stopTimer();boardElement.classList.add('paused');pauseButton.textContent='▶ Resume';messageElement.textContent='⏸ Game paused'}else{boardElement.classList.remove('paused');pauseButton.textContent='⏸ Pause';messageElement.textContent=started?'Keep going!':'Click a cell to start.';if(started)startTimer()}}
function hint(){if(gameOver||paused||hintUsed)return;hintUsed=true;const safe=all().filter(x=>!x.revealed&&!x.flagged&&!x.mine);if(!safe.length)return;const x=safe[Math.floor(Math.random()*safe.length)];x.element.classList.add('hint');setTimeout(()=>x.element.classList.remove('hint'),1200);hintButton.disabled=true;messageElement.textContent='💡 Hint: this cell is safe.'}
function daily(){const d=DIFFICULTIES.medium;difficultyElement.value='medium';rows=d.rows;cols=d.cols;mineTotal=d.mines;dailyMode=true;started=false;gameOver=false;revealedCount=0;flags=0;seconds=0;hintUsed=false;paused=false;stopTimer();timerElement.textContent='0';pauseButton.textContent='⏸ Pause';hintButton.disabled=false;messageElement.textContent='📅 Daily Challenge — same difficulty for everyone.';buildBoard();updateCounters();updateBest();dailyStatus.textContent='In progress'}
function theme(){document.body.classList.toggle('light');set('ms-theme',document.body.classList.contains('light')?'light':'dark');themeToggle.textContent=document.body.classList.contains('light')?'🌙':'☀️'}
function sound(){const on=get('ms-sound','on')==='on';set('ms-sound',on?'off':'on');soundToggle.textContent=on?'🔇':'🔊'}
function loadPrefs(){const light=get('ms-theme','dark')==='light';document.body.classList.toggle('light',light);themeToggle.textContent=light?'🌙':'☀️';soundToggle.textContent=get('ms-sound','on')==='on'?'🔊':'🔇'}
difficultyElement.addEventListener('change',newGame);newGameButton.addEventListener('click',newGame);pauseButton.addEventListener('click',togglePause);hintButton.addEventListener('click',hint);dailyButton.addEventListener('click',daily);themeToggle.addEventListener('click',theme);soundToggle.addEventListener('click',sound);loadPrefs();renderStats();newGame();
