const D={easy:{rows:9,cols:9,mines:10,xp:25,coins:10},medium:{rows:16,cols:16,mines:40,xp:60,coins:25},hard:{rows:16,cols:30,mines:99,xp:120,coins:60}};
const $=id=>document.getElementById(id);const board=$('board'),diff=$('difficulty'),msg=$('message');let R=9,C=9,M=10,cells=[],started=false,over=false,paused=false,revealed=0,flags=0,time=0,timer=null,hintUsed=false,daily=false;
const get=(k,d)=>{try{return localStorage.getItem(k)??d}catch(e){return d}},set=(k,v)=>{try{localStorage.setItem(k,v)}catch(e){}};
function P(){return{xp:+get('ms-xp','0'),level:+get('ms-level','1'),coins:+get('ms-coins','0'),streak:+get('ms-streak','0'),wins:+get('ms-wins','0'),games:+get('ms-games','0'),flags:+get('ms-total-flags','0'),reveals:+get('ms-reveals','0'),hardWins:+get('ms-hard-wins','0')}}
function save(p){Object.keys(p).forEach(k=>set('ms-'+k,p[k]))}function need(l){return 100+(l-1)*50}function rank(l){return l>=30?'Mine God':l>=20?'Grandmaster':l>=12?'Master':l>=7?'Expert':l>=3?'Explorer':'Rookie'}
function profile(){let p=P(),n=need(p.level);$('level').textContent=p.level;$('rank').textContent=rank(p.level);$('coins').textContent=p.coins;$('streak').textContent=p.streak;$('xp-text').textContent=`${p.xp} / ${n} XP`;$('xp-bar').style.width=Math.min(100,p.xp/n*100)+'%'}
function reward(x,c){let p=P();p.xp+=x;p.coins+=c;let up=0;while(p.xp>=need(p.level)){p.xp-=need(p.level);p.level++;up++}save(p);profile();return up}
function stats(){let p=P();$('wins').textContent=p.wins;$('games').textContent=p.games;$('win-rate').textContent=(p.games?Math.round(p.wins/p.games*100):0)+'%';profile();missions();achievements()}
function ns(r,c){let a=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;let rr=r+dr,cc=c+dc;if(rr>=0&&rr<R&&cc>=0&&cc<C)a.push(cells[rr][cc])}return a}function all(){return cells.flat()}
function shuffle(a){for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function build(){cells=[];board.replaceChildren();board.style.gridTemplateColumns=`repeat(${C},34px)`;for(let r=0;r<R;r++){let row=[];for(let c=0;c<C;c++){let x={r,c,mine:false,revealed:false,flagged:false,n:0,e:document.createElement('button')};x.e.className='cell';x.e.type='button';x.e.onclick=()=>reveal(r,c);x.e.oncontextmenu=e=>{e.preventDefault();flag(r,c)};row.push(x);board.appendChild(x.e)}cells.push(row)}}
function mines(fr,fc){let safe=new Set([`${fr},${fc}`,...ns(fr,fc).map(x=>`${x.r},${x.c}`)]),a=all().filter(x=>!safe.has(`${x.r},${x.c}`));if(a.length<M)a=all().filter(x=>x.r!==fr||x.c!==fc);shuffle(a);for(let i=0;i<M;i++)a[i].mine=true;all().forEach(x=>x.n=ns(x.r,x.c).filter(y=>y.mine).length)}
function render(x){x.e.className='cell';x.e.textContent='';if(x.flagged&&!x.revealed){x.e.classList.add('flagged');x.e.textContent='🚩';return}if(!x.revealed)return;x.e.classList.add('revealed');if(x.mine){x.e.classList.add('mine');x.e.textContent='💣'}else if(x.n)x.e.textContent=x.n}
function flood(s){let q=[s],seen=new Set();while(q.length){let x=q.shift(),k=x.r+','+x.c;if(seen.has(k)||x.revealed||x.flagged||x.mine)continue;seen.add(k);x.revealed=true;revealed++;render(x);if(!x.n)ns(x.r,x.c).forEach(y=>q.push(y))}}
function startClock(){if(timer===null&&!paused)timer=setInterval(()=>{$('timer').textContent=++time},1000)}function stopClock(){if(timer!==null){clearInterval(timer);timer=null}}
function reveal(r,c){if(over||paused)return;let x=cells[r][c];if(x.flagged)return;if(x.revealed){chord(x);return}if(!started){started=true;mines(r,c);startClock();msg.textContent='Clear every safe cell!'}if(x.mine){x.revealed=true;render(x);lose();return}flood(x);let p=P();p.reveals++;save(p);check()}
function chord(x){if(!started||!x.n)return;let a=ns(x.r,x.c);if(a.filter(y=>y.flagged).length!==x.n)return;for(let y of a){if(y.flagged||y.revealed)continue;if(y.mine){y.revealed=true;render(y);lose();return}flood(y)}check()}
function flag(r,c){if(over||paused)return;let x=cells[r][c];if(x.revealed||(!x.flagged&&flags>=M))return;x.flagged=!x.flagged;flags+=x.flagged?1:-1;let p=P();if(x.flagged)p.flags++;save(p);render(x);$('mine-count').textContent=Math.max(0,M-flags);$('flag-count').textContent=flags;missions();achievements()}
function revealMines(){all().forEach(x=>{if(x.mine){x.revealed=true;render(x)}})}
function lose(){over=true;stopClock();revealMines();let p=P();p.games++;p.streak=0;save(p);stats();msg.textContent='💥 Boom! Streak broken. Try again.'}
function check(){if(revealed!==R*C-M)return;over=true;stopClock();all().forEach(x=>{if(x.mine&&!x.flagged){x.flagged=true;flags++;render(x)}});let d=D[diff.value],p=P();p.games++;p.wins++;p.streak++;if(diff.value==='hard')p.hardWins++;save(p);let up=reward(d.xp,d.coins);let key='ms-best-'+diff.value,b=+get(key,'0'),record=!b||time<b;if(record)set(key,time);$('mine-count').textContent=0;$('flag-count').textContent=flags;$('best-time').textContent=(record?time:b)+'s';stats();msg.textContent=`🎉 WIN! +${d.xp} XP +${d.coins} 🪙${up?' • LEVEL UP!':''}${record?' • 🏆 NEW RECORD!':''}`;if(daily)$('daily-status').textContent='Completed!' }
function newGame(){let d=D[diff.value];R=d.rows;C=d.cols;M=d.mines;started=over=paused=daily=false;revealed=flags=time=0;hintUsed=false;stopClock();$('timer').textContent=0;$('mine-count').textContent=M;$('flag-count').textContent=0;$('pause-game').textContent='⏸ Pause';$('hint-button').disabled=false;board.classList.remove('paused');msg.textContent='Click a cell to start.';$('daily-status').textContent='Ready';$('best-time').textContent=(+get('ms-best-'+diff.value,'0')||'—')+(get('ms-best-'+diff.value,'0')?'s':'');build();stats()}
function pause(){if(over)return;paused=!paused;if(paused){stopClock();board.classList.add('paused');$('pause-game').textContent='▶ Resume';msg.textContent='⏸ Game paused'}else{board.classList.remove('paused');$('pause-game').textContent='⏸ Pause';msg.textContent=started?'Keep going!':'Click a cell to start.';if(started)startClock()}}
function hint(){if(over||paused||hintUsed)return;let a=all().filter(x=>!x.revealed&&!x.flagged&&!x.mine);if(!a.length)return;hintUsed=true;let x=a[Math.floor(Math.random()*a.length)];x.e.classList.add('hint');setTimeout(()=>x.e.classList.remove('hint'),1500);$('hint-button').disabled=true;msg.textContent='💡 A safe cell is highlighted.'}
function dailyGame(){diff.value='medium';daily=true;newGame();daily=true;$('daily-status').textContent='In progress';msg.textContent='📅 Daily Challenge — Medium board.'}
function missions(){if(!$('missions-list'))return;let p=P(),a=[['💣','Play 3 games',p.games,3,15],['🚩','Place 10 flags',p.flags,10,20],['🔓','Reveal 100 cells',p.reveals,100,25],['🔥','Reach a 3-win streak',p.streak,3,40]];$('missions-list').innerHTML=a.map(x=>`<div class="mission ${x[2]>=x[3]?'done':''}"><span class="mission-icon">${x[0]}</span><div class="mission-body"><strong>${x[1]}</strong><span>${Math.min(x[2],x[3])} / ${x[3]}</span><div class="mini-bar"><i style="width:${Math.min(100,x[2]/x[3]*100)}%"></i></div></div><b>${x[2]>=x[3]?'✓':'+'+x[4]+' XP'}</b></div>`).join('')}
function achievements(){if(!$('achievements-list'))return;let p=P(),a=[['First Blood','Win your first game',p.wins>=1],['Getting Good','Reach level 5',p.level>=5],['Hot Streak','Win 5 games in a row',p.streak>=5],['Flag Master','Place 100 flags',p.flags>=100],['Speed Demon','Set a best time',all().length>0&&!!+get('ms-best-'+diff.value,'0')],['Hardcore','Win Hard mode',p.hardWins>=1],['Veteran','Play 25 games',p.games>=25],['Mine God','Reach level 30',p.level>=30]],n=a.filter(x=>x[2]).length;$('achievement-count').textContent=n+' / '+a.length;$('achievements-list').innerHTML=a.map(x=>`<div class="achievement ${x[2]?'unlocked':''}"><span>${x[2]?'🏆':'🔒'}</span><div><strong>${x[0]}</strong><small>${x[1]}</small></div><b>${x[2]?'UNLOCKED':''}</b></div>`).join('')}
function tabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('tab-'+b.dataset.tab).classList.add('active')})}function theme(){document.body.classList.toggle('light');set('ms-theme',document.body.classList.contains('light')?'light':'dark');$('theme-toggle').textContent=document.body.classList.contains('light')?'🌙':'☀️'}function sound(){let on=get('ms-sound','on')==='on';set('ms-sound',on?'off':'on');$('sound-toggle').textContent=on?'🔇':'🔊'}
diff.onchange=newGame;newGameButton.onclick=newGame;$('pause-game').onclick=pause;$('hint-button').onclick=hint;$('daily-button').onclick=dailyGame;$('theme-toggle').onclick=theme;$('sound-toggle').onclick=sound;tabs();if(get('ms-theme','dark')==='light')document.body.classList.add('light');newGame();
